version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CATALOG_SERVICE_URL=http://catalog:5000
      - ORDER_SERVICE_URL=http://order:4000
    networks:
      - emporium-network
    extra_hosts:
      - "catalog:host-gateway"  # Allows connecting to catalog service on host machine

networks:
  emporium-network:
    driver: bridge
