services:
  gateway:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - CATALOG_SERVICES=http://host.docker.internal:5001,http://host.docker.internal:5002
      - ORDER_SERVICES=http://host.docker.internal:5003,http://host.docker.internal:5004
      - CACHE_ENABLED=true
      - CACHE_CAPACITY=100
      - CACHE_TTL=300000
    extra_hosts:
      - "host.docker.internal:host-gateway"
